identidock:
 build: .
 ports:
  - 5000:9090
 environment:
  ENV: DEV
 volumes :
  - ./app:/app
 links:
  - dnmonster
  - redis
#name of the other containers.
dnmonster:
  image: amouat/dnmonster:1.0

redis:
  image: "redis:alpine"
